### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by danielecr** [lagun4ik/docker-gogs#1]
during install step
specified gogs/gogs as user/pass for db, and anything else leaved untouched

**Comment by Hser2bio** [comment]
Hi! @danielecr 

use last image of mariadb  and works fine

**Comment by danielecr** [comment]
> Hi! @danielecr
> 
> use last image of mariadb and works fine

This report is very old, I can not remember the steps to reproduce.
Anyway this repo is old as well, and the `docker-compose.yml` define `image: mariadb:10.1`, and that file is part (or the most important part) of this repository.
A more sensible reply would have been to send a pull request with that change, but I understand that this report is really uncomplete without steps to reproduce (a real "test case", if there was a test folder ... I see that travis has docker-compose build, and not `up`)

Also this docker-compose refer to latest gogs, and not a specific version. So, it is more likely that to the real fix comes from the newer gogs, and not from the latest mariadb.
I am closing this because I am not using and I can not give more information

... reviewing it I see mariadb:10.1-??, ok, this is no well defined and this ambiguous configuration should be avoided, another reason to just close this.
